theme = "catppuccin_mocha"


[editor]
line-number = "relative"
cursorline = true
color-modes = true
auto-save = true
soft-wrap.enable = true
bufferline = "always"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true
display-messages = true

[editor.indent-guides]
render = true

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

# A-h = "delete_char_backward"
# A-j = "insert_newline"
# A-k = "kill_to_line_end"



[keys.normal]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


[editor.file-picker]
hidden = false

[keys.normal."+"]
e = ":run-shell-command echo hi"



